########################################################################################################################
## Example FGF14
########################################################################################################################

fastq_dir: FGF14_fastq/
results: results/

whitelist:
  - FGF14_00001
  - FGF14_00002
  
motifs:
  - AAG
  - GAG
  - AGG
  - ACG
  - AAC

filter_repeats:
  - AAGAAG
  - AAGAAG_absent

## reverse_complement: True # FGF14 on -strand!

flanking_region:
  upstream:   ATATCAATATTCTCTATGCAACCAA # 25 bp
  downstream: TAGAAATGTGTTTAAGAATTCCTCA # 25 bps

motif_colors:
  AAG: "#5ca2d5"
  GAG: "yellow"
  AGG: "red"
  ACG: "brown"
  AAC: "pink"
  other: "black"

alleles_yaml: resources/alleles/FGF14.alleles.yaml


#########################################################################################################################
## general configuration
#########################################################################################################################

verbose: True


## tools

fastqc:
  adapters: resources/ont/ont_adapters.fastqc.tsv

bbduk:
  default: t=4 pigz=t unpigz=t
  filtering: -Xmx2g qin=33 minlen=200 qtrim=lr trimq=10 maq=10 maxlen=100000

repeat_region_spanning:
  edit_distance: 2

