########################################################################################################################
## Example FGF14
########################################################################################################################


########################################################################################################################
## 007_FGF14
## FGF14__region_of_interest_for_IGV__hg38 (13:102161316-102161992)
########################################################################################################################

# fastq_dir: input/run007_FGF14.sup.fastq
# results: results/run007_FGF14/ont-guppy_6.4.6/sup

# whitelist:
#   - FGF14_45618
#   - FGF14_79607
#   - FGF14_80329
#   - FGF14_80331
#   - FGF14_80332
#   - FGF14_80357
#   - FGF14_80431
#   - FGF14_80545
#   - FGF14_80548
#   - FGF14_80689
#   - FGF14_80920
#   - FGF14_80996
#   - FGF14_81456
#   - FGF14_81457
#   - FGF14_82415
#   - FGF14_82898
#   - FGF14_83825
#   - FGF14_84267
#   - FGF14_84415
#   - FGF14_86967
#   - FGF14_87668
#   - FGF14_87859
#   - FGF14_88489
#   - FGF14_90120
#   - FGF14_90982
#   - FGF14_91143
#   - FGF14_91231
#   - FGF14_91423
#   - FGF14_92042
#   - FGF14_93354
#   - FGF14_93578
#   - FGF14_93580
#   - FGF14_95081
#   - FGF14_95289
#   - FGF14_95404
#   - FGF14_95405
#   - FGF14_95406
#   - FGF14_95407
#   - FGF14_95408
#   - FGF14_95411
#   - FGF14_95412
#   - FGF14_95716
#   - FGF14_96397
#   - FGF14_96642
#   - FGF14_96652
#   - FGF14_96701
#   - FGF14_96714
#   - FGF14_96715
#   - FGF14_97038


########################################################################################################################
## run008_run009_FGF14_NIPBL_OGT_CGI
## FGF14__region_of_interest_for_IGV__hg38 (13:102161316-102161992)
########################################################################################################################

# fastq_dir: input/run008_run009_FGF14.sup.fastq
# results: results/run008_run009_FGF14/ont-guppy_6.4.6/sup

# whitelist:
#   - FGF14_45631
#   - FGF14_80330
#   - FGF14_81356
#   - FGF14_83637
#   - FGF14_88619
#   - FGF14_89829
#   - FGF14_91410
#   - FGF14_91412
#   - FGF14_91413
#   - FGF14_91439
#   - FGF14_91440
#   - FGF14_92794
#   - FGF14_97038
#   - FGF14_97526
#   - FGF14_97638
#   - FGF14_97787
#   - FGF14_97791
#   - FGF14_97799
#   - FGF14_97800
#   - FGF14_98270
#   - FGF14_990099
#   - FGF14_990418
#   - FGF14_990658
#   - FGF14_990667
#   - FGF14_990789
#   - FGF14_990808
#   - FGF14_990832
#   - FGF14_990843 # problematic!
#   - FGF14_991065
#   - FGF14_991234
#   - FGF14_991423
#   - FGF14_991437
#   - FGF14_991699
#   - FGF14_991887
#   - FGF14_992073
#   - FGF14_992102
#   - FGF14_992356
#   - FGF14_992712
#   - FGF14_992745
#   - FGF14_992749
#   - FGF14_992974
#   - FGF14_993150
#   - FGF14_993649
#   - FGF14_993690
#   - FGF14_993743
#   - FGF14_994109
#   - FGF14_994326
#   - FGF14_994434
#   - FGF14_994752
#   - FGF14_994955
#   - FGF14_994991
#   - FGF14_994994
#   - FGF14_995498
#   - FGF14_995602
#   - FGF14_995731
#   - FGF14_996151
#   - FGF14_996612
#   - FGF14_996698
#   - FGF14_996722
#   - FGF14_996889
#   - FGF14_996918
#   - FGF14_996956
#   - FGF14_997022
#   - FGF14_997633
#   - FGF14_997817
#   - FGF14_998125
#   - FGF14_998171
#   - FGF14_998201
#   - FGF14_998295
#   - FGF14_998326
#   - FGF14_998535
#   - FGF14_998552
#   - FGF14_998557
#   - FGF14_998668
#   - FGF14_998750
#   - FGF14_998780
#   - FGF14_998795
#   - FGF14_998894
#   - FGF14_998895
#   - FGF14_999007
#   - FGF14_999161
#   - FGF14_999197


########################################################################################################################
## run010_run011_20230920_FGF14_FAME_NAA10
## FGF14__region_of_interest_for_IGV__hg38 (13:102161316-102161992)
########################################################################################################################

# fastq_dir: input/run010_run011_FGF14.sup.fastq
# results: results/run010_run011_FGF14/ont-guppy_6.4.6/sup

# whitelist:
#   - FGF14_98072
#   - FGF14_98343


#########################################################################################################################
## run012_20231107_FGF14
## FGF14__region_of_interest_for_IGV__hg38 (13:102161316-102161992)
#########################################################################################################################

# fastq_dir: input/run012_FGF14.sup.fastq
# results: results/run012_FGF14/ont-guppy_6.4.6/sup

# whitelist:
#   - FGF14_97062
#   - FGF14_87909
#   - FGF14_98902
#   - FGF14_96397
#   - FGF14_96714
#   - FGF14_96642
#   - FGF14_96642_run7


#########################################################################################################################
## run014_20240515_FGF14_MARCH6_NAA_DAB_AFF
## FGF14__region_of_interest_for_IGV__hg38 (13:102161316-102161992)
#########################################################################################################################

fastq_dir: input/run014_20240515_FGF14_MARCH6_NAA_DAB_AFF.sup.fastq
results: results/run014_20240515_FGF14_MARCH6_NAA_DAB_AFF_new/ont-guppy_6.4.6/sup

whitelist:
  # - AFF2_Ctrl_IP
  # - AFF2_c0001T_aunt
  # - AFF2_c0001_pt
  # - AFF2_c0001b_mother
  # - DAB1_100505

  # - FGF14_100148
  # - FGF14_100389
  # - FGF14_100781
  # - FGF14_100782

  - FGF14_101502 # no allele
  - FGF14_101503 # no allele
  # - FGF14_101504 # no allele
  # - FGF14_101505 # no allele
  # - FGF14_101507 # no allele
  # - FGF14_101508 # no allele
  # - FGF14_101510 # no allele
  # - FGF14_101511 # no allele
  # - FGF14_101512 # no allele
  # - FGF14_101513 # no allele
  # - FGF14_101514 # no allele
  # - FGF14_101515 # no allele
  # - FGF14_101516 # no allele
  # - FGF14_101518 # no allele
  # - FGF14_101519 # no allele
  # - FGF14_101520 # no allele
  # - FGF14_101521 # no allele
  # - FGF14_101522 # no allele
  # - FGF14_101523 # no allele
  # - FGF14_101524 # no allele
  # - FGF14_101604 # no allele
  # - FGF14_101605 # no allele
  # - FGF14_101606 # no allele
  # - FGF14_101607 # no allele

#   - FGF14_101765
#   - FGF14_101766
#   - FGF14_101767
#   - FGF14_84415
#   - FGF14_96859
#   - FGF14_99310
#   - FGF14_99439
#   - FGF14_99599

#   ## - MARCHF6_100949
#   ## - MARCHF6_100950
#   ## - MARCHF6_101921
#   ## - MARCHF6_101924
#   ## - MARCHF6_97368
#   ## - NAA10_F_R1_100767
#   ## - NAA10_F_R1_55042
#   ## - NAA10_F_R1_55043
#   ## - NAA10_F_R1_95716
#   ## - NAA10_F_R2_100767
#   ## - NAA10_F_R2_55042
#   ## - NAA10_F_R2_55043
#   ## - NAA10_F_R2_95716


########################################################################################################################
## FGF14 settings
########################################################################################################################

motifs:
  - AAG
  - GAG
  - AGG
  - ACG
  - AAC

filter_repeats:
  - AAGAAG
  - AAGAAG_absent

## reverse_complement: True # FGF14 on -strand!

flanking_region:
  upstream:   ATATCAATATTCTCTATGCAACCAA # 25 bp, upstream_flanking_region, 13:102161532-102161557  # rc: TTGGTTGCATAGAGAATATTGATAT
  downstream: TAGAAATGTGTTTAAGAATTCCTCA # 25 bp, downstream_flanking_region 13:102161726-102161751 # rc: TGAGGAATTCTTAAACACATTTCTA

motif_colors:
  AAG: "#5ca2d5"  # blue
  GAG: "yellow"
  AGG: "red"
  ACG: "lime"
  AAC: "pink"
  other: "black"

alleles_yaml: resources/alleles/FGF14.v5.alleles.yaml


#########################################################################################################################
## general configuration
#########################################################################################################################

verbose: True


## tools

fastqc:
  adapters: resources/ont/ont_adapters.fastqc.tsv

bbduk:
  default: t=4 pigz=t unpigz=t
  filtering: -Xmx2g qin=33 minlen=200 qtrim=lr trimq=10 maq=10 maxlen=100000

repeat_region_spanning:
  edit_distance: 2

